### ISSUE TITLE
What's the fps of MDNet using GPU?

### ISSUE THREAD

**Issue by hiyijian** [HyeonseobNam/MDNet#1]
hi @HyeonseobNam ,
   Would you please to tell the fps you achieved in your test environment?
   The following is my testcase. Is that closed to yours?

Initialization...
  extract features...
  training cnn...
im2col: CUDA kernel error (invalid texture reference)
Processing frame 2/215... 2.725772 seconds
Processing frame 3/215... 2.145009 seconds
Processing frame 4/215... 1.917557 seconds
Processing frame 5/215... 2.628119 seconds
Processing frame 6/215... 2.196728 seconds
Processing frame 7/215... 1.892060 seconds
Processing frame 8/215... 2.746299 seconds
Processing frame 9/215... 2.051056 seconds
Processing frame 10/215...

**Comment by HyeonseobNam** [comment]
Hi,
The fps in our environment (8 cores of Xeon E5-2660 and a K20m) is about
0.9 fps in average, while the VOT committee reported it as 0.87 fps in
their environment.
Note that the fps highly depends the frequency of the network updates
(especially short-term updates), which is determined by the characteristic
of the sequence you are testing.

Best regards,
hyeonseob

2016-03-25 15:59 GMT+09:00 hiyijian <notifications@github.com>:
