### ISSUE TITLE
SRE and TRE results on OTB100

### ISSUE THREAD

**Issue by LostXine** [HyeonseobNam/MDNet#10]
Hi @HyeonseobNam , 
Thank you for your brilliant work. 
Recently when I tried to evaluate MDNet on OTB100 in detail, it seemed that only OPE results are available on your webpage. Therefore, I wonder if there is any chance to get SRE and TRE results of MDNet from your completed work?
Best Wishes!

**Comment by HyeonseobNam** [comment]
Hi, @LostXine 
Thank you for your interest in out work.
Unfortunately, we have not performed SRE or TRE on the OTB dataset. Sorry about the inconvenience :(

**Comment by LostXine** [comment]
That's okay with me, thanks for your reply :)
