### ISSUE TITLE
'disableDropout' argument inside mdnet_features_convX.m

### ISSUE THREAD

**Issue by HungWei-Andy** [HyeonseobNam/MDNet#5]
Hi, I have tried to run the demo on my computer. Below is my enviroment. 
> Ubuntu 14.04 LTS
> Memory 15.6 GB
> CPU: Intel® Core™ i7-6700K @ 4.00GHz × 8
> Graphics: GeForce GTX TITAN X/PCIe/SSE2

After I compiled and installed the newest version of MatConvNet, I follow the instructions to run the demo. However, I come across the error below.

> Error using vl_argparse (line 99)
> Unknown parameter 'disableDropout'

> Error in vl_simplenn (line 239)
> opts = vl_argparse(opts, varargin);

> Error in mdnet_features_convX (line 22)
>     res = vl_simplenn(net, batch, [], [], ...

> Error in mdnet_run (line 37)
>     feat_conv = mdnet_features_convX(net_conv, img, pos_examples, opts);

> Error in demo_tracking (line 22)
> result = mdnet_run(conf.imgList, conf.gt(1,:), net);

> Error in run (line 96)
> evalin('caller', [script ';']);

I think this is due to the 'disableDropout' argument in line 23 of mdnet_features_convX.m where vl_simplenn of MatConvNet does not handle this argument ( both the newest version of MatConvnet and the one attached in this repository, below is line 227-236 of vl_simplenn where opts do not contain 'disableDropout' ). 
I think this argument may be used to disable the default dropout setting of an older version of MatConvNet. But I am not quite sure. What is this argument for and what is the version of MatConvNet implementing MDNet? Is there something I didn't notice? Thank you!

> opts.conserveMemory = false ;
> opts.sync = false ;
> opts.mode = 'normal' ;
> opts.accumulate = false ;
> opts.cudnn = true ;
> opts.backPropDepth = +inf ;
> opts.skipForward = false ;
> opts.parameterServer = [] ;
> opts.holdOn = false ;
> opts = vl_argparse(opts, varargin);

**Comment by HungWei-Andy** [comment]
Sorry, it seems my mistake to add the path of the newest version of MatConvNet to the default path of matlab. So, when I thought matlab is using the MatConvNet in this repository, it actually ran the newest version. The MatConvNet in this repository should work. Sorry for this stupid question~

**Comment by wduo** [comment]
???
