### ISSUE TITLE
Using custom dataset with MDNet

### ISSUE THREAD

**Issue by rezkitrianto** [HyeonseobNam/MDNet#6]
Hi @HyeonseobNam, 
I was trying to tweak the MDNet code with another custom dataset, which is VT77 dataset (http://cmp.felk.cvut.cz/~vojirtom/dataset/). I see in the training process, that MDNet use the sequence from multiple tracking sequences and needs to generate the sequence list first in `pretraining/seqList`. What is this list used for and how to generate this by using another dataset?

Thanks in advance

**Comment by HungWei-Andy** [comment]
I have watched most codes in this repository. First, I think the information of the sequences used in pretraining and tracking is retrieved by util/getConfig.m where the dataset name and the seq name are specified as inputs.
    In pretraining, the dataset name and the txt file containing the sequence names are specfied. Below are some codes in pretraining/demo_pretraining. The argument seqsList is a cell array whose cells are structures with attribute 'dataset' and 'list' which is the dataset name and the txt file containing the sequence names.

`mdnet_pretrain('seqsList',...`
`    {struct('dataset','vot2013','list','pretraining/seqList/vot13-otb.txt'),...`
`    struct('dataset','vot2014','list','pretraining/seqList/vot14-otb.txt'),...`
`    struct('dataset','vot2015','list','pretraining/seqList/vot15-otb.txt')},...`
`    'outFile', fullfile('models','mdnet_vot-otb_new.mat'),...`
`    'roiDir', fullfile('models','data_vot-otb'));`

Therefore, I guess if you want to train on your own dataset, you only need to add new dataset in util/getConfig and specify the dataset name and the path to the txt file.

**Comment by HungWei-Andy** [comment]
Plus, if your image format is neither 'jpg' nor 'png', remember to transform them into 'jpg' or 'png' format.

**Comment by HungWei-Andy** [comment]
It's better to watch the codes before asking this.

**Comment by rezkitrianto** [comment]
thanks for the answer @HungWei-Andy!
Yes I've done all the things mentioned and had successfully applied this to custom dataset. I wanted to make sure first since I've got not a very good result on this dataset. 
Thanks again! cheers :+1:
