### ISSUE TITLE
the 'demo_tracking.m' aborted when runs hundreds of frames

### ISSUE THREAD

**Issue by zhengzhugithub** [HyeonseobNam/MDNet#7]
Processing frame 137/315... 1.266084 seconds
Processing frame 138/315... 1.483625 seconds
Processing frame 139/315... Warning: A worker aborted during execution of the parfor loop. The parfor loop will
now run again on the remaining workers. 
> In parallel_function at 596
  In mdnet_extract_regions at 17
  In mdnet_features_convX at 9
  In mdnet_run at 166
  In demo_tracking at 22
  In run at 63 
Error using parallel_function (line 604)
All workers aborted during execution of the parfor loop.

Error in mdnet_extract_regions (line 17)
parfor i = 1:num_boxes

Error in mdnet_features_convX (line 9)
ims = mdnet_extract_regions(img, boxes, opts);

Error in mdnet_run (line 166)
        feat_conv = mdnet_features_convX(net_conv, img, examples, opts);

Error in demo_tracking (line 22)
result = mdnet_run(conf.imgList, conf.gt(1,:), net);

Error in run (line 63)
evalin('caller', [script ';']);
 
The client lost connection to worker 1. This might be due to network problems, or
the interactive communicating job might have errored.

**Comment by HyeonseobNam** [comment]
@zhengzhugithub 
A simple solution is using 'for' instead of 'parfor' in mdnet_extract_regions if you don't care about some speed drop. If you want to keep using parfor, this [post](https://codeyarns.com/2016/02/23/matlab-parallel-pool-error/) might be helpful :)

**Comment by zhengzhugithub** [comment]
thank you
